inherit_gem:
  ezcater_rubocop: conf/rubocop_gem.yml

plugins:
  - rubocop-capybara

AllCops:
    TargetRubyVersion: 3.0
    SuggestExtensions: false

Naming/FileName:
  Exclude:
  - "lib/activerecord-postgres_pub_sub.rb"

Naming/MemoizedInstanceVariableName:
  Exclude:
  - "lib/generators/active_record/postgres_pub_sub/notify_on_insert_generator.rb"
