inherit_gem:
  ezcater_rubocop: conf/rubocop.yml

Naming/FileName:
  Exclude:
  - "lib/activerecord-postgres_pub_sub.rb"

# TODO: renable after open-sourcing ezcater_matchers
Ezcater/RspecMatchOrderedArray:
  Enabled: false
