name: CI
on:
  pull_request:
  push:
    branches: [ main ]

env:
  branch: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref_name }}

jobs:
  lint:
    name: Lint (Ruby ${{ matrix.ruby }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.2' ]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependencies
        run: bundle install

      - name: Run Rubocop
        run: bundle exec rubocop

  test:
    name: Test (Ruby ${{ matrix.ruby }}, activerecord ${{ matrix.activerecord }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        activerecord: [ '6.1', '7.0', '7.1', '7.2', '8.0' ]
        ruby: [ '3.2', '3.3', '3.4' ]
        exclude:
          - activerecord: '6.1'
            ruby: '3.4'
          - activerecord: '7.0'
            ruby: '3.4'
    timeout-minutes: 10
    needs:
      - lint

    env:
      PGUSER: postgres

    services:
      postgres:
        image: postgres:16.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres_pub_sub_test
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install postgresql-client
        run: sudo apt update && sudo apt install postgresql-client

      - name: Install activerecord_${{ matrix.activerecord }} dependencies
        run: BUNDLE_GEMFILE=gemfiles/activerecord_${{ matrix.activerecord }}.gemfile bundle install

      - name: Appraise activerecord_${{ matrix.activerecord }}
        run: bundle exec appraisal activerecord_${{ matrix.activerecord }} rspec
